const titles = ['The Bible', 
                'Don Quixote', 
                'A Tale of Two Cities', 
                'The Lord of the Rings', 
                'The Little Prince', 
                'Harry Potter and the Sorcerers Stone',
                'And Then There Were None',
                'The Dream of The Red Chamber',
                'She: A History of Adventure',
                'The Lion, the Witch and the Wardrobe',
                'The Da Vinci Code',
                'Think and Grow Rich',
                'Harry Potter and the Chamber of Secrets',
                'Harry Potter and the Prisoner of Azkaban',
                'Harry Potter and the Goblet of Fire',
                'Harry Potter and the Order of the Pheonix',
                'Harry Potter and the Deathly Hallows',
                'One Hundred Years of Solitude',
                'Lolita',
                'Anne of Green Gables',
                'Charlottes Web',
                'Black Beauty'
            ];

export {titles};